// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file user/v1/api.proto (package user.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { CreateUserRequestSchema, CreateUserResponseSchema, GetUserRequestSchema, GetUserResponseSchema, VerifyUserRequestSchema, VerifyUserResponseSchema } from "./user_api_pb";
import { file_user_v1_user_api } from "./user_api_pb";

/**
 * Describes the file user/v1/api.proto.
 */
export const file_user_v1_api: GenFile = /*@__PURE__*/
  fileDesc("ChF1c2VyL3YxL2FwaS5wcm90bxIHdXNlci52MTLZAQoLVXNlclNlcnZpY2USRQoKQ3JlYXRlVXNlchIaLnVzZXIudjEuQ3JlYXRlVXNlclJlcXVlc3QaGy51c2VyLnYxLkNyZWF0ZVVzZXJSZXNwb25zZRI8CgdHZXRVc2VyEhcudXNlci52MS5HZXRVc2VyUmVxdWVzdBoYLnVzZXIudjEuR2V0VXNlclJlc3BvbnNlEkUKClZlcmlmeVVzZXISGi51c2VyLnYxLlZlcmlmeVVzZXJSZXF1ZXN0GhsudXNlci52MS5WZXJpZnlVc2VyUmVzcG9uc2VCjAEKC2NvbS51c2VyLnYxQghBcGlQcm90b1ABWjZnaXRodWIuY29tL3NhemFqdW4xMzkwL3VzZXIvcGtnL2dlbi9idWYvdXNlci92MTt1c2VydjGiAgNVWFiqAgdVc2VyLlYxygIHVXNlclxWMeICE1VzZXJcVjFcR1BCTWV0YWRhdGHqAghVc2VyOjpWMWIGcHJvdG8z", [file_user_v1_user_api]);

/**
 * Tokenサービス
 *
 * @generated from service user.v1.UserService
 */
export const UserService: GenService<{
  /**
   * ユーザーを作成するAPI
   *
   * @generated from rpc user.v1.UserService.CreateUser
   */
  createUser: {
    methodKind: "unary";
    input: typeof CreateUserRequestSchema;
    output: typeof CreateUserResponseSchema;
  },
  /**
   * Tokenを取得するAPI
   *
   * @generated from rpc user.v1.UserService.GetUser
   */
  getUser: {
    methodKind: "unary";
    input: typeof GetUserRequestSchema;
    output: typeof GetUserResponseSchema;
  },
  /**
   * 仮登録を検証するAPI
   *
   * @generated from rpc user.v1.UserService.VerifyUser
   */
  verifyUser: {
    methodKind: "unary";
    input: typeof VerifyUserRequestSchema;
    output: typeof VerifyUserResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_user_v1_api, 0);

