// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file user/v1/user_api.proto (package user.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { User, UserToken } from "./user_pb";
import { file_user_v1_user } from "./user_pb";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file user/v1/user_api.proto.
 */
export const file_user_v1_user_api: GenFile = /*@__PURE__*/
  fileDesc("ChZ1c2VyL3YxL3VzZXJfYXBpLnByb3RvEgd1c2VyLnYxIp4BChFDcmVhdGVVc2VyUmVxdWVzdBIbCgp1c2VyX2VtYWlsGAEgASgJQge6SARyAmABEiAKCHBhc3N3b3JkGAIgASgJQgm6SAZyBBABGBRIAIgBARIwCgh1c2VyX3RlbBgDIAEoCUIZukgWchQyEl5cKzgxWy0wLTldezksMTN9JEgBiAEBQgsKCV9wYXNzd29yZEILCglfdXNlcl90ZWwiMQoSQ3JlYXRlVXNlclJlc3BvbnNlEhsKBHVzZXIYASABKAsyDS51c2VyLnYxLlVzZXIidwoYQ3JlYXRlVXNlclByb2ZpbGVSZXF1ZXN0EhsKCnVzZXJfZW1haWwYASABKAlCB7pIBHICYAESEQoJdXNlcl9uYW1lGAIgASgJEisKCHVzZXJfdGVsGAMgASgJQhm6SBZyFDISXlwrODFbLTAtOV17OSwxM30kIjgKGUNyZWF0ZVVzZXJQcm9maWxlUmVzcG9uc2USGwoEdXNlchgBIAEoCzINLnVzZXIudjEuVXNlciJFChFWZXJpZnlVc2VyUmVxdWVzdBIYChB1c2VyX3Jlc291cmNlX2lkGAEgASgJEhYKDnZlcmlmeV9tZXNzYWdlGAIgASgJIlkKElZlcmlmeVVzZXJSZXNwb25zZRIbCgR1c2VyGAEgASgLMg0udXNlci52MS5Vc2VyEiYKCnVzZXJfdG9rZW4YAiABKAsyEi51c2VyLnYxLlVzZXJUb2tlbiJKCg5HZXRVc2VyUmVxdWVzdBIbCgp1c2VyX2VtYWlsGAEgASgJQge6SARyAmABEhsKCHBhc3N3b3JkGAIgASgJQgm6SAZyBBABGBQiLgoPR2V0VXNlclJlc3BvbnNlEhsKBHVzZXIYASABKAsyDS51c2VyLnYxLlVzZXJCkAEKC2NvbS51c2VyLnYxQgxVc2VyQXBpUHJvdG9QAVo2Z2l0aHViLmNvbS9zYXphanVuMTM5MC91c2VyL3BrZy9nZW4vYnVmL3VzZXIvdjE7dXNlcnYxogIDVVhYqgIHVXNlci5WMcoCB1VzZXJcVjHiAhNVc2VyXFYxXEdQQk1ldGFkYXRh6gIIVXNlcjo6VjFiBnByb3RvMw", [file_user_v1_user, file_buf_validate_validate]);

/**
 * @generated from message user.v1.CreateUserRequest
 */
export type CreateUserRequest = Message<"user.v1.CreateUserRequest"> & {
  /**
   * ユーザーEmail
   *
   * @generated from field: string user_email = 1;
   */
  userEmail: string;

  /**
   * パスワード
   * OAuth2では使用しない
   *
   * @generated from field: optional string password = 2;
   */
  password?: string;

  /**
   * ユーザー電話番号
   *
   * @generated from field: optional string user_tel = 3;
   */
  userTel?: string;
};

/**
 * Describes the message user.v1.CreateUserRequest.
 * Use `create(CreateUserRequestSchema)` to create a new message.
 */
export const CreateUserRequestSchema: GenMessage<CreateUserRequest> = /*@__PURE__*/
  messageDesc(file_user_v1_user_api, 0);

/**
 * レスポンステスト用
 *
 * @generated from message user.v1.CreateUserResponse
 */
export type CreateUserResponse = Message<"user.v1.CreateUserResponse"> & {
  /**
   * Userリソース
   *
   * @generated from field: user.v1.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message user.v1.CreateUserResponse.
 * Use `create(CreateUserResponseSchema)` to create a new message.
 */
export const CreateUserResponseSchema: GenMessage<CreateUserResponse> = /*@__PURE__*/
  messageDesc(file_user_v1_user_api, 1);

/**
 * ユーザーProfile作成
 *
 * @generated from message user.v1.CreateUserProfileRequest
 */
export type CreateUserProfileRequest = Message<"user.v1.CreateUserProfileRequest"> & {
  /**
   * ユーザーEmail
   *
   * @generated from field: string user_email = 1;
   */
  userEmail: string;

  /**
   * ユーザー名
   *
   * @generated from field: string user_name = 2;
   */
  userName: string;

  /**
   * ユーザー電話番号
   *
   * @generated from field: string user_tel = 3;
   */
  userTel: string;
};

/**
 * Describes the message user.v1.CreateUserProfileRequest.
 * Use `create(CreateUserProfileRequestSchema)` to create a new message.
 */
export const CreateUserProfileRequestSchema: GenMessage<CreateUserProfileRequest> = /*@__PURE__*/
  messageDesc(file_user_v1_user_api, 2);

/**
 * レスポンステスト用
 *
 * @generated from message user.v1.CreateUserProfileResponse
 */
export type CreateUserProfileResponse = Message<"user.v1.CreateUserProfileResponse"> & {
  /**
   * Userリソース
   *
   * @generated from field: user.v1.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message user.v1.CreateUserProfileResponse.
 * Use `create(CreateUserProfileResponseSchema)` to create a new message.
 */
export const CreateUserProfileResponseSchema: GenMessage<CreateUserProfileResponse> = /*@__PURE__*/
  messageDesc(file_user_v1_user_api, 3);

/**
 * SingUpの認証用
 *
 * @generated from message user.v1.VerifyUserRequest
 */
export type VerifyUserRequest = Message<"user.v1.VerifyUserRequest"> & {
  /**
   * UserリソースID
   *
   * @generated from field: string user_resource_id = 1;
   */
  userResourceId: string;

  /**
   * 認証用メッセージ
   *
   * @generated from field: string verify_message = 2;
   */
  verifyMessage: string;
};

/**
 * Describes the message user.v1.VerifyUserRequest.
 * Use `create(VerifyUserRequestSchema)` to create a new message.
 */
export const VerifyUserRequestSchema: GenMessage<VerifyUserRequest> = /*@__PURE__*/
  messageDesc(file_user_v1_user_api, 4);

/**
 * 成功時にJWTを返す
 *
 * @generated from message user.v1.VerifyUserResponse
 */
export type VerifyUserResponse = Message<"user.v1.VerifyUserResponse"> & {
  /**
   * Userリソース
   *
   * @generated from field: user.v1.User user = 1;
   */
  user?: User;

  /**
   * UserToken
   *
   * @generated from field: user.v1.UserToken user_token = 2;
   */
  userToken?: UserToken;
};

/**
 * Describes the message user.v1.VerifyUserResponse.
 * Use `create(VerifyUserResponseSchema)` to create a new message.
 */
export const VerifyUserResponseSchema: GenMessage<VerifyUserResponse> = /*@__PURE__*/
  messageDesc(file_user_v1_user_api, 5);

/**
 * UserTokenリクエストテスト用
 *
 * @generated from message user.v1.GetUserRequest
 */
export type GetUserRequest = Message<"user.v1.GetUserRequest"> & {
  /**
   * userResourceId
   *
   * @generated from field: string user_email = 1;
   */
  userEmail: string;

  /**
   * パスワード
   *
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message user.v1.GetUserRequest.
 * Use `create(GetUserRequestSchema)` to create a new message.
 */
export const GetUserRequestSchema: GenMessage<GetUserRequest> = /*@__PURE__*/
  messageDesc(file_user_v1_user_api, 6);

/**
 * レスポンステスト用
 *
 * @generated from message user.v1.GetUserResponse
 */
export type GetUserResponse = Message<"user.v1.GetUserResponse"> & {
  /**
   * UserResorce
   *
   * @generated from field: user.v1.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message user.v1.GetUserResponse.
 * Use `create(GetUserResponseSchema)` to create a new message.
 */
export const GetUserResponseSchema: GenMessage<GetUserResponse> = /*@__PURE__*/
  messageDesc(file_user_v1_user_api, 7);

