// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file user/v1/user.proto (package user.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_validate_validate } from "../../validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file user/v1/user.proto.
 */
export const file_user_v1_user: GenFile = /*@__PURE__*/
  fileDesc("ChJ1c2VyL3YxL3VzZXIucHJvdG8SB3VzZXIudjEiiQMKBFVzZXISDwoHdXNlcl9pZBgBIAEoCRISCgp1c2VyX2VtYWlsGAIgASgJEhYKCXVzZXJfbmFtZRgDIAEoCUgAiAEBEhUKCHVzZXJfdGVsGAQgASgJSAGIAQESOAoKY3JlYXRlZF9hdBgFIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBCCPpCBbIBAggBEjMKCnVwZGF0ZWRfYXQYBiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wSAKIAQESMwoKZGVsZXRlZF9hdBgHIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBIA4gBARI6ChFwdXJnZWRfZXhwaXJlc19hdBgIIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBIBIgBAUIMCgpfdXNlcl9uYW1lQgsKCV91c2VyX3RlbEINCgtfdXBkYXRlZF9hdEINCgtfZGVsZXRlZF9hdEIUChJfcHVyZ2VkX2V4cGlyZXNfYXQiGgoJVXNlclRva2VuEg0KBXRva2VuGAEgASgJQo0BCgtjb20udXNlci52MUIJVXNlclByb3RvUAFaNmdpdGh1Yi5jb20vc2F6YWp1bjEzOTAvdXNlci9wa2cvZ2VuL2J1Zi91c2VyL3YxO3VzZXJ2MaICA1VYWKoCB1VzZXIuVjHKAgdVc2VyXFYx4gITVXNlclxWMVxHUEJNZXRhZGF0YeoCCFVzZXI6OlYxYgZwcm90bzM", [file_google_protobuf_timestamp, file_validate_validate]);

/**
 * Userメッセージ
 *
 * @generated from message user.v1.User
 */
export type User = Message<"user.v1.User"> & {
  /**
   * ユーザーID
   *
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * ユーザーEmail
   *
   * @generated from field: string user_email = 2;
   */
  userEmail: string;

  /**
   * ユーザー名
   *
   * @generated from field: optional string user_name = 3;
   */
  userName?: string;

  /**
   * ユーザー電話番号
   *
   * @generated from field: optional string user_tel = 4;
   */
  userTel?: string;

  /**
   * 作成日時
   *
   * @generated from field: google.protobuf.Timestamp created_at = 5;
   */
  createdAt?: Timestamp;

  /**
   * 更新日時
   *
   * @generated from field: optional google.protobuf.Timestamp updated_at = 6;
   */
  updatedAt?: Timestamp;

  /**
   * 削除日時
   *
   * @generated from field: optional google.protobuf.Timestamp deleted_at = 7;
   */
  deletedAt?: Timestamp;

  /**
   * 物理削除予定日
   *
   * @generated from field: optional google.protobuf.Timestamp purged_expires_at = 8;
   */
  purgedExpiresAt?: Timestamp;
};

/**
 * Describes the message user.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_user_v1_user, 0);

/**
 * UserTokenメッセージ
 *
 * @generated from message user.v1.UserToken
 */
export type UserToken = Message<"user.v1.UserToken"> & {
  /**
   * Token
   * jwtを返す
   *
   * @generated from field: string token = 1;
   */
  token: string;
};

/**
 * Describes the message user.v1.UserToken.
 * Use `create(UserTokenSchema)` to create a new message.
 */
export const UserTokenSchema: GenMessage<UserToken> = /*@__PURE__*/
  messageDesc(file_user_v1_user, 1);

